### ISSUE TITLE
Suggestion: Don't generate preview when url is enclosed by <>

### ISSUE THREAD

**Issue by craftwar** [canaria3406/ermiana#11]
Respect the poster's invention.

**Comment by canaria3406** [comment]
Is there any example message?

**Comment by craftwar** [comment]
any url  enclosed in <>
ex: <https://google.com>
![image](https://github.com/canaria3406/ermiana/assets/16416710/0f129280-6ff6-4153-9628-adf87f510023)
The second message is the same url but encoded by <>.
