### ISSUE TITLE
[Question] Escape an URL

### ISSUE THREAD

**Issue by ytingyeu** [canaria3406/ermiana#12]
Currently I use spoiler message to avoid triggering the BOT if I do not want the message to be analyzed. Is there method other than spoiler message to do escape?

**Comment by canaria3406** [comment]
I have no idea if there is any feature on discord can do that... 
But you can try this:
![0](https://github.com/canaria3406/ermiana/assets/27627468/12c26e87-b409-4df6-b97c-f54b172dbfd3)
