### ISSUE TITLE
[Enhancement] 增加個別關閉/開啟各網站預覽的指令

### ISSUE THREAD

**Issue by MayouKurayami** [canaria3406/ermiana#16]
有些本來就有預覽的網站或其他不需要機器人產生預覽的情況，希望能增加對特定網站關閉/開啟預覽的功能

例:
/disable site:baha
/enable site:baha

**Comment by canaria3406** [comment]
BOT會對網站的原生預覽做消除喔  
請檢查BOT的`管理訊息`權限是否正常運作，否則確實會干擾版面
![圖片](https://github.com/canaria3406/ermiana/assets/27627468/13007b09-1be3-42c7-b434-1a47271fb7b8)

**Comment by MayouKurayami** [comment]
其實還是有一些邊緣案例會想關掉某些網站的預覽
(比較喜歡原生預覽，或跟其他機器人衝突之類的)

不過有對原生預覽做消除這點確實讓這功能的需求減低不少

**Comment by canaria3406** [comment]
了解  
未來有時間的話應該會寫這個功能  
如果有特定網站預覽格式建議的話也可以在這邊提🙏

**Comment by MayouKurayami** [comment]
> 如果有特定網站預覽格式建議的話也可以在這邊提🙏

推特影片的原生預覽+機器人預覽會重複縮圖，有點浪費版面
![image](https://github.com/canaria3406/ermiana/assets/52200840/23f88258-bdb5-4b2c-a650-c663a290dd4b)


再加上色圖的原生預覽經常是空的，所以可能直接一律砍掉推特的原生預覽比較好

**Comment by CharlesChiuGit** [comment]
agree. 我目前也有用 https://github.com/everettsouthwick/embetter 來做threads和ig的預覽
我目前的解法是關掉embetter bot的推特預覽
